priority: 10

onEvent('recipes', event => {
  //EE hammer recipes
  event.remove({id: 'ftbic:shaped/roller'})

  event.remove({id: 'emendatusenigmatica:dust_from_chunk/apatite'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/silver'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/sapphire'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/potassium_nitrate'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/lead'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/lapis'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/certus_quartz'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/cobalt'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/uranium'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/dimensional'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/coal'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/emerald'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/iron'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/copper'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/peridot'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/aluminum'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/quartz'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/gold'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/sulfur'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/diamond'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/fluorite'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/tin'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/zinc'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/nickel'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/osmium'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/ruby'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/cinnabar'})
  event.remove({id: 'ftbic:shapeless/sulfur_from_hammer'})
  event.remove({id: 'emendatusenigmatica:dust_from_chunk/iridium'})

  event.remove({id: 'emendatusenigmatica:dust_from_ore/quartz'})

  event.remove({id: 'emendatusenigmatica:plate_from_gem/emerald'})
  event.remove({id: 'emendatusenigmatica:plate_from_gem/sapphire'})
  event.remove({id: 'emendatusenigmatica:plate_from_gem/diamond'})
  event.remove({id: 'emendatusenigmatica:plate_from_gem/peridot'})
  event.remove({id: 'emendatusenigmatica:plate_from_gem/lapis'})
  event.remove({id: 'emendatusenigmatica:plate_from_gem/ruby'})

  event.remove({id: 'emendatusenigmatica:plate_from_ingot/copper'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/iridium'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/lead'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/signalum'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/osmium'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/enderium'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/bronze'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/steel'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/iron'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/tin'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/brass'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/uranium'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/silver'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/lumium'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/electrum'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/constantan'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/cobalt'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/gold'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/aluminum'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/cast_iron'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/zinc'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/invar'})
  event.remove({id: 'emendatusenigmatica:plate_from_ingot/nickel'})
})