onEvent('recipes', event => {
	///////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////
	/////DONT REMOVE!	///////////////////////////////////////
	///////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////
                                                       
event.shaped('1x create:deployer', ['ABC','DEF','GHI'], {A: 'minecraft:air',B: 'create:electron_tube',C: 'minecraft:air',D: 'create:cogwheel',E: 'create:andesite_casing',F: 'create:cogwheel',G: 'minecraft:air',H: 'kubejs:zinc_hand',I: 'minecraft:air'})
event.shaped('1x create:electron_tube', ['ABC','DEF','GHI'], {A: 'minecraft:air',B: 'minecraft:red_stained_glass_pane',C: 'minecraft:air',D: 'minecraft:air',E: 'minecraft:torch',F: 'minecraft:air',G: 'minecraft:air',H: '#forge:nuggets/copper',I: 'minecraft:air'})
event.shaped('1x create:mechanical_press', ['ABC','DEF','GHI'], {A: 'minecraft:air',B: 'create:andesite_alloy',C: 'minecraft:air',D: 'create:cogwheel',E: 'create:andesite_casing',F: 'create:cogwheel',G: 'minecraft:air',H: '#forge:storage_blocks/zinc',I: 'minecraft:air'})
event.shapeless('1x minecraft:flint_and_steel', ['minecraft:flint','twilightforest:knightmetal_ingot'])                                                      
event.shaped('1x twilightforest:knightmetal_pickaxe', ['ABC','DEF','GHI'], {A: 'twilightforest:knightmetal_ingot',B: 'twilightforest:knightmetal_ingot',C: 'twilightforest:knightmetal_ingot',D: 'minecraft:air',E: 'immersiveengineering:stick_treated',F: 'minecraft:air',G: 'minecraft:air',H: 'immersiveengineering:stick_treated',I: 'minecraft:air'})
event.shaped('1x appliedenergistics2:charger', ['ABC','DEF','GHI'], {A: 'minecraft:iron_ingot',B: 'appliedenergistics2:certus_quartz_crystal',C: 'minecraft:iron_ingot',D: 'minecraft:iron_ingot',E: 'appliedenergistics2:certus_quartz_crystal',F: 'minecraft:air',G: 'minecraft:iron_ingot',H: 'appliedenergistics2:certus_quartz_crystal',I: 'minecraft:iron_ingot'})
event.shaped(Item.of('immersiveengineering:blueprint', '{blueprint:"electrode"}'), ['ABC','DEF','GHI'], {A: '#forge:storage_blocks/steel',B: '#forge:storage_blocks/steel',C: '#forge:storage_blocks/steel',D: 'minecraft:blue_dye',E: 'minecraft:blue_dye',F: 'minecraft:blue_dye',G: 'minecraft:paper',H: 'minecraft:paper',I: 'minecraft:paper'})
event.shaped('1x boss_tools:iron_engine', ['ABC','DEF','GHI'], {A: 'kubejs:duraluminium_ingot',B: 'minecraft:redstone',C: 'kubejs:duraluminium_ingot',D: 'kubejs:duraluminium_plate',E: 'kubejs:duraluminium_gear',F: 'boss_tools:engine_frame',G: 'kubejs:duraluminium_ingot',H: 'minecraft:redstone',I: 'kubejs:duraluminium_plate'})
event.shaped('1x boss_tools:engine_frame', ['ABC','DEF','GHI'], {A: 'kubejs:duraluminium_ingot',B: 'kubejs:duraluminium_plate',C: 'kubejs:duraluminium_ingot',D: 'kubejs:duraluminium_plate',E: 'minecraft:air',F: 'kubejs:duraluminium_plate',G: 'kubejs:duraluminium_ingot',H: 'kubejs:duraluminium_plate',I: 'kubejs:duraluminium_ingot'})
event.shaped('1x boss_tools:rocket_nose_cone', ['ABC','DEF','GHI'], {A: 'twilightforest:snow_queen_trophy',B: 'twilightforest:yeti_trophy',C: 'twilightforest:ur_ghast_trophy',D: 'twilightforest:knight_phantom_trophy',E: 'kubejs:duraluminium_gear',F: 'twilightforest:lich_trophy',G: 'twilightforest:minoshroom_trophy',H: 'twilightforest:hydra_trophy',I: 'twilightforest:naga_trophy'})
event.shaped('1x boss_tools:iron_tank', ['ABC','DEF','GHI'], {A: 'kubejs:duraluminium_ingot',B: 'twilightforest:fiery_ingot',C: 'kubejs:duraluminium_ingot',D: 'twilightforest:fiery_ingot',E: 'twilightforest:fiery_tears',F: 'twilightforest:fiery_ingot',G: 'kubejs:duraluminium_ingot',H: 'twilightforest:fiery_ingot',I: 'kubejs:duraluminium_ingot'})
event.shaped('1x boss_tools:rocket_fin', ['ABC','DEF','GHI'], {A: 'minecraft:air',B: 'kubejs:duraluminium_ingot',C: 'minecraft:air',D: 'kubejs:duraluminium_plate',E: 'kubejs:duraluminium_ingot',F: 'kubejs:duraluminium_plate',G: 'boss_tools:compressed_steel',H: 'kubejs:duraluminium_ingot',I: 'boss_tools:compressed_steel'})
event.shaped('1x boss_tools:nasa_workbench', ['ABC','DEF','GHI'], {A: 'kubejs:duraluminium_ingot',B: 'avaritia:double_compressed_crafting_table',C: 'kubejs:duraluminium_ingot',D: 'kubejs:duraluminium_plate',E: 'kubejs:duraluminium_gear',F: 'kubejs:duraluminium_plate',G: 'kubejs:duraluminium_ingot',H: 'avaritia:double_compressed_crafting_table',I: 'kubejs:duraluminium_ingot'})
event.shaped('1x ars_nouveau:ritual_moonfall', ['ABC','DEF','GHI'], {A: 'ars_nouveau:blue_archwood_log',B: 'minecraft:ink_sac',C: 'ars_nouveau:blue_archwood_log',D: 'minecraft:ink_sac',E: 'minecraft:coal_block',F: 'minecraft:ink_sac',G: 'ars_nouveau:blue_archwood_log',H: 'minecraft:ink_sac',I: 'ars_nouveau:blue_archwood_log'})
event.shaped('1x ars_nouveau:ritual_sunrise', ['ABC','DEF','GHI'], {A: 'ars_nouveau:red_archwood_log',B: '#forge:gems/mana',C: 'ars_nouveau:red_archwood_log',D: '#forge:gems/mana',E: 'minecraft:dandelion',F: '#forge:gems/mana',G: 'ars_nouveau:red_archwood_log',H: '#forge:gems/mana',I: 'ars_nouveau:red_archwood_log'})
event.shaped('1x ars_nouveau:arcane_relay', ['ABA', 'ACA', 'ABA'], {A: '#forge:ingots/copper',B: 'minecraft:air',C: 'ars_nouveau:mana_gem_block'})
event.shaped('1x ars_nouveau:mana_condenser', ['ABA', 'CDC', 'ABA'], {A: 'minecraft:air',B: '#forge:gems/mana',C: '#forge:ingots/copper',D: 'minecraft:wheat'})
event.shaped('1x ars_nouveau:arcane_core', ['AAA', 'BCB', 'AAA'], {A: 'ars_nouveau:arcane_stone',B: '#forge:ingots/copper',C: 'minecraft:air'})
event.shaped('1x ars_nouveau:crystallizer', ['ABA', 'ACA', 'ABA'], {A: '#forge:ingots/copper',B: 'ars_nouveau:arcane_stone', C: '#forge:gems/mana'})
event.shaped('1x ars_nouveau:enchanting_apparatus', ['ABA', 'ACA', 'DDD'], {A: '#forge:ingots/zinc',B: '#forge:glass/purple',C: 'minecraft:air',D: 'ars_nouveau:arcane_stone'})
event.shapeless('1x ars_nouveau:novice_spell_book', ['minecraft:book', 'minecraft:stone_pickaxe', 'minecraft:stone_shovel', 'minecraft:stone_hoe', 'minecraft:stone_axe', 'minecraft:stone_sword', ])
event.shaped('1x productivebees:powered_centrifuge', ['ABC','DEF','GHI'], {A: 'minecraft:redstone',B: 'minecraft:iron_ingot',C: 'minecraft:redstone',D: 'kubejs:duraluminium_ingot',E: 'productivebees:centrifuge',F: 'kubejs:duraluminium_ingot',G: 'minecraft:redstone',H: 'minecraft:iron_ingot',I: 'minecraft:redstone'})                                                
event.shapeless('4x astralsorcery:marble_raw', ['boss_tools:moon_stone','boss_tools:moon_stone','boss_tools:moon_stone','boss_tools:moon_stone','boss_tools:moon_stone','boss_tools:moon_stone'])
event.shaped('1x ars_nouveau:glyph_press', ['ABC','DEF','GHI'], {A: 'ars_nouveau:warding_stone',B: 'ars_nouveau:warding_stone',C: 'ars_nouveau:warding_stone',D: 'ars_nouveau:warding_stone',E: 'ars_nouveau:enchanting_apparatus',F: 'ars_nouveau:warding_stone',G: 'ars_nouveau:warding_stone',H: 'ars_nouveau:mana_gem_block',I: 'ars_nouveau:warding_stone'})
event.shaped('1x ars_nouveau:magic_clay', ['ABC','DEF','GHI'], {A: 'minecraft:clay_ball',B: 'ars_nouveau:mana_gem',C: 'minecraft:air',D: 'ars_nouveau:blank_parchment',E: 'ars_nouveau:mana_gem',F: 'minecraft:air',G: 'minecraft:air',H: 'minecraft:air',I: 'minecraft:air'})
event.shaped('1x immersiveengineering:hammer', ['ABC','DEF','GHI'], {A: 'minecraft:air',B: '#forge:ingots/copper',C: 'minecraft:string',D: 'minecraft:air',E: 'minecraft:stick',F: '#forge:ingots/copper',G: 'minecraft:stick',H: 'minecraft:air',I: 'minecraft:air'})
event.shaped('1x toms_storage:ts.inventory_connector', ['ABC','DEF','GHI'], {A: 'immersiveengineering:treated_wood_horizontal',B: 'minecraft:ender_pearl',C: 'immersiveengineering:treated_wood_horizontal',D: 'minecraft:chest',E: 'minecraft:lapis_block',F: 'minecraft:chest',G: 'immersiveengineering:treated_wood_horizontal',H: 'ars_nouveau:mana_gem',I: 'immersiveengineering:treated_wood_horizontal'})
event.shaped('1x toms_storage:ts.storage_terminal', ['ABC','DEF','GHI'], {A: 'twilightforest:ironwood_ingot',B: 'minecraft:stone',C: 'twilightforest:ironwood_ingot',D: 'immersiveengineering:treated_wood_horizontal',E: 'twilightforest:naga_trophy',F: 'immersiveengineering:treated_wood_horizontal',G: 'twilightforest:ironwood_ingot',H: 'minecraft:stone',I: 'twilightforest:ironwood_ingot'})
event.shaped('1x toms_storage:ts.crafting_terminal', ['ABC','DEF','GHI'], {A: 'minecraft:crafting_table',B: 'minecraft:obsidian',C: 'minecraft:crafting_table',D: 'minecraft:obsidian',E: 'toms_storage:ts.storage_terminal',F: 'minecraft:obsidian',G: 'minecraft:crafting_table',H: 'minecraft:obsidian',I: 'minecraft:crafting_table'})
event.shaped('1x minecraft:compass', ['ABC','DEF','GHI'], {A: 'minecraft:air',B: '#forge:ingots/copper',C: 'minecraft:air',D: '#forge:ingots/copper',E: 'minecraft:arrow',F: '#forge:ingots/copper',G: 'minecraft:air',H: '#forge:ingots/copper',I: 'minecraft:air'})
event.shaped('1x immersive_aircraft:propeller', ['ABC','DEF','GHI'], {A: 'minecraft:air',B: 'emendatusenigmatica:zinc_plate',C: 'emendatusenigmatica:zinc_plate',D: 'minecraft:air',E: 'emendatusenigmatica:zinc_plate',F: 'minecraft:air',G: 'emendatusenigmatica:zinc_plate',H: 'emendatusenigmatica:zinc_plate',I: 'minecraft:air'})
event.shaped('1x immersive_aircraft:hull', ['ABC','DEF','GHI'], {A: '#minecraft:planks',B: '#minecraft:planks',C: '#minecraft:planks',D: '#forge:ingots/zinc',E: '#forge:ingots/zinc',F: '#forge:ingots/zinc',G: '#minecraft:planks',H: '#minecraft:planks',I: '#minecraft:planks'})
event.shaped('1x immersive_aircraft:engine', ['ABC','DEF','GHI'], {A: 'minecraft:air',B: '#forge:cobblestone',C: 'minecraft:air',D: 'immersive_aircraft:boiler',E: 'minecraft:furnace',F: 'immersive_aircraft:boiler',G: '#forge:cobblestone',H: 'ars_nouveau:ritual_sunrise',I: '#forge:cobblestone'})
event.shaped('1x immersive_aircraft:boiler', ['ABC','DEF','GHI'], {A: '#forge:ingots/copper',B: '#forge:ingots/copper',C: '#forge:ingots/copper',D: '#forge:ingots/copper',E: 'minecraft:air',F: '#forge:ingots/copper',G: '#forge:ingots/copper',H: 'minecraft:furnace',I: '#forge:ingots/copper'})
event.shaped('1x immersive_aircraft:enhanced_propeller', ['ABC','DEF','GHI'], {A: '#forge:ingots/zinc',B: '#forge:ingots/zinc',C: 'minecraft:air',D: 'minecraft:air',E: 'immersive_aircraft:propeller',F: 'minecraft:air',G: 'minecraft:air',H: '#forge:ingots/zinc',I: '#forge:ingots/zinc'})
event.shaped('1x immersive_aircraft:industrial_gears', ['ABC','DEF','GHI'], {A: 'minecraft:air',B: '#forge:ingots/copper',C: '#forge:ingots/copper',D: '#forge:ingots/zinc',E: 'minecraft:lever',F: '#forge:ingots/copper',G: '#forge:ingots/zinc',H: '#forge:ingots/zinc',I: 'minecraft:air'})
event.shapeless('1x primutils:chopping_block', ['#minecraft:logs'])
event.shaped('1x create:mechanical_saw', ['ABC','DEF','GHI'], {A: 'minecraft:air',B: 'emendatusenigmatica:zinc_plate',C: 'minecraft:air',D: 'emendatusenigmatica:zinc_plate',E: '#forge:ingots/zinc',F: 'emendatusenigmatica:zinc_plate',G: 'minecraft:air',H: 'create:andesite_casing',I: 'minecraft:air'})

})//////DONT ADD MORE CODE AFTER THIS LINE
